# First 3 lines generated by di-pyoperator - DO NOT CHANGE (Deleted again when uploaded.)
from utils.mock_di_api import mock_api
api = mock_api(__file__)


def gen() :

    # config parameter 
    #api.config.data = None   # datatype : array

    for i,d in enumerate(api.config.data) :
        lastmsg = True if i == len(api.config.data)-1 else False
        attributes = {'operator':'dispatcher','message.indexBatch':i,'message.lastBatch':lastmsg}
        msg = api.Message(attributes= attributes, body = d)
        api.send('data',msg)

api.add_generator(gen)